### PR TITLE
SB-18158 - Proxy for etextbook APIs

### PR DESCRIPTION
**Pull request by maheshkumargangula**

### CODE REVIEW

**Comment by rjshrjndrn** [comment]
@SMY-ALTAMASH can you please have a look ?

**Comment by SMYALTAMASH** [comment]
Sure, @maheshkumargangula please update the sheet

**Comment by maheshkumargangula** [comment]
@SMYALTAMASH - Please merge this ASAP. The staging deployment requires this change.
Cc: @gandham-santhosh

**Comment by SMYALTAMASH** [comment]
Merged @maheshkumargangula , have created a new category for these APIs, will update you more on this in the meeting.

**Pull request merged**
