### PR TITLE
Adding ACL in Kong_all_consumer_groups for Public API's (SL)

### PR DESCRIPTION
**Pull request by sivakarthikeyanoptit**
Adding ACL in Kong_all_consumer_groups for Public API's (SL)

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Enhancement (additive changes to improve performance)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Tested in shikshalokam dev
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by SMYALTAMASH** [comment]
Please add this in private repo under specific consumer

**Comment by sivakarthikeyanoptit** [comment]
@SMYALTAMASH Currently, there are different APIs for different types of observation. Merging all these APIs into a single parameterized API which can handle all these reports.

https://project-sunbird.atlassian.net/browse/SB-23906   --jira ticket

**Comment by SMYALTAMASH** [comment]
@keshavprasadms there is a UI functionality which required the app to call apis in the KONG, so it need to be enabled in this consumer, please review from your end and merge this,

**Review by keshavprasadms — APPROVED** [review]
Looks good. All ACLs are backed by JWT and RL as medium.

**Pull request merged**
