### PR TITLE
Added env. variable in player service

### PR DESCRIPTION
**Pull request by anujtech46**
Player service used a variable **sunbird_explore_button_visibility**. Which is not available in sunbird_player.env .

### CODE REVIEW

**Comment by anujtech46** [comment]
@rjshrjndrn , @SMYALTAMASH . Please check and merge.

**Comment by anujtech46** [comment]
In sunbird 1.9 release **sunbird_explore_button_visibility** this variable is missing.

**Comment by anujtech46** [comment]
@rjshrjndrn @SMYALTAMASH

**Comment by rjshrjndrn** [comment]
closing as having merge conflicts. Please rebase and raise a new one

**Pull request closed without merging**
