### PR TITLE
SC-1270

### PR DESCRIPTION
**Pull request by anmol2302**
<b>Ticket Ref: </b> [SC-1270](https://project-sunbird.atlassian.net/browse/SC-1270)
<b>DOC :</b> [Onboarding APIs Reference](https://docs.google.com/spreadsheets/d/15fQRG1D8D214XhbLh-RKv078SJ2Au1_nXDMbsbUnpLc/edit#gid=772094723)
<h3> Onboarding of Reset Password ,Identifier FreeUp APIs , mergeUserAccounts API , Certificate Addition & Certificate Validation</h3>
1: `/private/user/v1/identifier/freeup` : API added in sheet and added in kong-API->defaults-main.yml . </br>
2: `/private/user/v1/password/reset`: API added in sheet and added in kong-API->defaults-main.yml. <br/>
3: `/private/user/v1/account/merge`: API added in sheet and added in kong-API->defaults-main.yml. </br>
4: `/private/user/v1/certs/add` : API added in sheet and added in kong-API->defaults-main.yml . </br>
5: `/private/user/v1/certs/validate`: API added in sheet and added in kong-API->defaults-main.yml. <br/>
<b> Note:  ALL THE ABOVE APIS ARE JUST ONBOARDED FOR TESTING IN DEV ENVIRONMENT AFTER TESTING THESE APIs WE NEED TO <u>DEBOARD</u> THEM AS WELL.</b>

### CODE REVIEW

**Comment by anmol2302** [comment]
> @anmol2302 the acl should not be public as it is a restricted API and cannot be publicuser

@SMY-ALTAMASH  all the above mention API we are onboarding them for testing purpose(easy to be tested by the portal team and others) after testing of APIs we will remove them.
cc: @manzarul

**Comment by gandham-santhosh** [comment]
@anmol2302 this is a risk for dev environment if these API's are onboarded with public access. Please update the ACL

**Comment by anmol2302** [comment]
> @anmol2302 this is a risk for dev environment if these API's are onboarded with public access. Please update the ACL

@gandham-santhosh these APIs protected by the API key, there is no harm in  onboarding these APIs with public access
cc: @manzarul

**Comment by SMYALTAMASH** [comment]
it is a risk on user management if these apis are under publicUser acl as we will be creating different consumers for the apis.

**Pull request merged**
