### PR TITLE
Issue #ED-2632 fix: removed unused env variables and added OCI endpoint variable

### PR DESCRIPTION
**Pull request by abhishekpnt**
<table>
<td>
  <a href="https://project-sunbird.atlassian.net/browse/ED-2632" title="ED-2632" target="_blank">Sub-taskED-2632</a>  Portal CSP changes
  </td></table>
  <br />
 

…nt variable

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Enhancement (additive changes to improve performance)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by rajeevsathish — APPROVED** [review]

**Review by gandham-santhosh — COMMENTED** [review]
@abhishekpnt I still see few variables referencing to azure. Can you please check them?

**Comment by abhishekpnt** [comment]
@gandham-santhosh i have cleaned up all variables referencing to AZURE. But we dont know the impact. Other services which might be using them might fail
cc: @rajeevsathish

**Comment by gandham-santhosh** [comment]
@abhishekpnt this env file is specific to Ed portal. I hope you have removed all the references of azure in the portal code base

**Comment by abhishekpnt** [comment]
Yes @gandham-santhosh . I have removed all references of azure in portal codebase

**Review by gandham-santhosh — APPROVED** [review]

**Pull request merged**
